add stingray_vision and stingray_vision_msgs pkgs
hidronautics/stingray pull request #7
Opened 2020-10-25 19:23 UTC by vladushked

add opencv dnn support

2020-10-25 22:16 UTC, TimeEscaper requested changes
В целом все ок, только вот эти в основном косметические вещи поправить ну и ответить где я тебя спрашивал.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +    package_name_with_net = rospy.get_param('~package_name_with_net')
Этот параметр думаю можно для сокращения назвать `net_package`.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +        print("Shutting down {} node".format(rospy.get_name()))
Здесь то же самое про логгирование.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +        weights_path = os.path.sep.join(
Ты тестил да этот резолвинг пути?

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +    def deleteMultipleObjects(self, objects):
Можешь плиз добавить коммент для чего эта функция нужна?

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +            img, size=(300, 300), swapRB=True, crop=False))
Тут кстати интересный момент, ты получается ресайзишь до размера 300x300?

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/package.xml
> +  <description>The stingray_vision package</description>
В идеале бы добавить чуть более красивое описание)))) Но не обязательно.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision_msgs/package.xml
> +  <description>The stingray_vision_msgs package</description>
Здесь тоже по-красивее бы описание, но по желанию.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/launch/object_detector.launch
> +    <arg name="videofile_path" default="/home/vladushked/Documents/hydro/dnn_gate_detector/run_detection_scripts/video/2.mp4" />
В дефолтных параметрах не должно быть абсолютных путей из твоей системы. Ты можешь показать пример в пути в комментариях как вариант.

2020-10-25 22:16 UTC, TimeEscaper commented on src/stingray_vision/CMakeLists.txt
> +  scripts/opencv_dnn_detector.py
Ты же выставил права на выполнение этого файла, да?

2020-10-26 05:32 UTC, vladushked commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +        weights_path = os.path.sep.join(
Нормально работает да

2020-10-26 05:32 UTC, vladushked commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +        weights_path = os.path.sep.join(
Собственно здесь я не менял ничего, в старой ноде это еще было

2020-10-26 05:39 UTC, vladushked commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +    def deleteMultipleObjects(self, objects):
Добавил

2020-10-26 05:40 UTC, vladushked commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +            img, size=(300, 300), swapRB=True, crop=False))
Да, потому что на вход нейронка такое принимает

2020-10-26 06:07 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +            img, size=(300, 300), swapRB=True, crop=False))
Вообще стоит на самом деле попробовать потом потестить точность при разных размерах этого параметра, потому что по идее тензорфлоу во время обучения и валидации должен работать с исходным изображением без ресайза. В общем я думаю стоит добавить этот размер для ресайза как параметр, можно как один параметр, через запятую передавать размеры: 300,300

2020-10-26 06:13 UTC, TimeEscaper requested changes
Ну в общем от меня все, только тот момент с ресайзом.

2020-10-27 11:56 UTC, vladushked commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +            img, size=(300, 300), swapRB=True, crop=False))
Вообще вроде тензорфлоу тоже ресайзит при обучении
Тут у самой модели вроде input 300 на 300

2020-10-27 13:12 UTC, TimeEscaper approved these changes

2020-10-27 13:12 UTC, TimeEscaper commented on src/stingray_vision/scripts/opencv_dnn_detector.py
> +        rospy.loginfo(type(self.input_size_x))
Потом удали в каком-нибудь другом коммите)

2020-10-27 13:12 UTC, merged